sudo: true
language: python

python:
  - 2.7

addons:
  postgresql: "9.1"

services:
  - postgresql

before_script: 
  - sudo apt-get install -y postgresql-server-dev-all 
  - export PATH="/usr/lib/postgresql/9.1/bin:$PATH"
  - echo $PATH
  - git clone https://github.com/segasai/q3c.git
  - which psql
  - pg_config --version
  - psql --version
  - which pg_config
  - cd q3c/
  - make
  - sudo make install
  - cd ../
  - psql -U postgres -c 'CREATE USER goto'
  - psql -U postgres -c 'CREATE DATABASE wsdb'
  - psql -U postgres -c "ALTER USER goto WITH PASSWORD '$GOTO_PASSWORD'"
  - psql -U postgres -c 'ALTER DATABASE wsdb OWNER TO goto'
  - psql -U postgres -d wsdb -c 'create extension q3c'
  - which psql

script:
  - ls -lh
  - which psql

#after_success:
#  - coveralls

notifications:
  email:
    recipients:
      - andrew.casey@monash.edu 
    on_success: change
    on_failure: change

