sudo: true
language: python
python:
  - 2.7

compiler:
  - clang
  - gcc

env:
  matrix:
    - PGVERSION=9.6
    - PGVERSION=9.5
    - PGVERSION=9.4
    - PGVERSION=9.3
    - PGVERSION=9.2
    - PGVERSION=9.1

before_install:
  # Set up PostgreSQL
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg-testing main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - createuser -U postgres -s travis
  # Download and install Q3C
  - git clone https://github.com/segasai/q3c.git
  - cd q3c
  - make
  - sudo make install
  - cd ../
  # Set up goto/wdsb relationship
  - psql -U postgres -c 'CREATE USER goto'
  - psql -U postgres -c 'CREATE DATABASE wsdb'
  - psql -U postgres -c "ALTER USER goto WITH PASSWORD '$GOTO_PASSWORD'"
  - psql -U postgres -c 'ALTER DATABASE wsdb OWNER TO goto'
  - psql -U postgres -d wsdb -c 'CREATE EXTENSION q3c'
  
install:
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=wsdb 

#after_success:
#  - coveralls

notifications:
  email:
    recipients:
      - andrew.casey@monash.edu 
    on_success: change
    on_failure: change

