psql -U postgres -d wsdb -a -f gaiadr1_tgas_source_schema
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-000.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-001.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-002.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-003.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-004.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-005.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-006.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-007.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-008.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-009.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-010.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-011.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-012.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-013.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-014.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -d wsdb -a -c "COPY gaiadr1_tgas_source FROM '/goto-db/catalogs/gaiadr1.tgas_source/TgasSource_000-000-015.csv' WITH ( FORMAT CSV, HEADER );"
psql -U postgres -a -c "GRANT SELECT ON TABLE gaiadr1_tgas_source TO goto;"
psql -U postgres -d wsdb -h localhost -a -c "CREATE INDEX ON gaiadr1_tgas_source (q3c_ang2ipix(ra, dec));"
psql -U postgres -d wsdb -h localhost -a -c "CLUSTER gaiadr1_tgas_source_q3c_ang2ipix_idx ON gaiadr1_tgas_source;"
psql -U postgres -d wsdb -h localhost -a -c "ANALYZE gaiadr1_tgas_source;"
