wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/twomass_psc_schema
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aaa.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aab.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aac.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aad.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aae.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aaf.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aag.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aah.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aai.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aaj.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aak.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aal.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aam.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aan.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aao.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aap.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aaq.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aar.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aas.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aat.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aau.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aav.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aaw.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aax.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aay.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aaz.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aba.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abb.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abc.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abd.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abe.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abf.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abg.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abh.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abi.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abj.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abk.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abl.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abm.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abn.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abo.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abp.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abq.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abr.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abs.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abt.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abu.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abv.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abw.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abx.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aby.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_abz.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_aca.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_acb.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_acc.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_acd.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_ace.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_baa.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bab.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bac.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bad.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bae.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_baf.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bag.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bah.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bai.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_baj.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bak.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bal.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bam.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_ban.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bao.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bap.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_baq.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bar.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bas.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bat.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bau.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bav.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_baw.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bax.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bay.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_baz.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bba.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbb.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbc.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbd.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbe.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbf.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbg.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbh.gz
wget -nc http://irsa.ipac.caltech.edu/2MASS/download/allsky/psc_bbi.gz
gunzip -v psc_*.gz
